config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :talkers,   only: [:new, :create, :show]
  resources :schedules, only: [:index]

  namespace :admin do
    get :dashboard, to: 'dashboard#index'

    resources :listeners

    resources :schedules do
      member do
        resource :finish, only: [:new, :create], controller: 'schedules/finish'
      end
    end

    resources :talkers, only: [] do
      resource :schedule, only: [:new, :create, :show], controller: 'talkers/schedules'
    end
  end

  root to: 'talkers#new'
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    def index
      @talkers_without_schedule       = Talker.without_schedule
      @talkers_waiting_for_session    = Talker.waiting_for_session
      @talkers_waiting_for_occurrence = Talker.waiting_for_occurrence
    end
  end
end

app/views/admin/dashboard/index.html.erb
<h1>Dashboard</h1>

<h2>
  Falantes pendentes
  <small>Falantes aguardando para a confirmação do agendamento</small>
</h2>

<% if @talkers_without_schedule.any? %>
  <table class='table'>
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>Data de interesse</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
    <% @talkers_without_schedule.each do |talker | %>
      <tr>
        <td><%= talker.name %></td>
        <td><%= talker.email %></td>
        <td><%= talker.phone %></td>
        <td><%=l talker.forecast_at, format: :short %></td>
        <td>
          <%= link_to 'Agendar', new_admin_talker_schedule_path(talker) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>Sem falantes aguardando por agendamento</p>
<% end %>

<h2>
  Falantes aguardando
  <small>Falantes aguardando pelo início da sessão</small>
</h2>

<% if @talkers_waiting_for_session.any? %>
  <table class='table'>
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>Agendado para</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
    <% @talkers_waiting_for_session.each do |talker | %>
      <tr>
        <td><%= talker.name %></td>
        <td><%= talker.email %></td>
        <td><%= talker.phone %></td>
        <td><%=l talker.schedule.scheduled_to, format: :short %></td>
        <td>
          <%= link_to 'Sala', talker.schedule.room_url %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>Sem falantes aguardando pelo início da sessão</p>
<% end %>

<h2>
  Sessões ocorridas
  <small>Sessões ocorridas e que necessitam de finalização</small>
</h2>

<% if @talkers_waiting_for_occurrence.any? %>
  <table class='table'>
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>Agendado para</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
    <% @talkers_waiting_for_occurrence.each do |talker| %>
      <tr>
        <td><%= talker.name %></td>
        <td><%= talker.email %></td>
        <td><%= talker.phone %></td>
        <td><%=l talker.schedule.scheduled_to, format: :short %></td>
        <td>
          <%= link_to 'Finalizar!', new_admin_finish_path(talker.schedule) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>Sem sessões necessitando de finalização</p>
<% end %>