config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :talkers,   only: [:new, :create, :show]
  resources :schedules, only: [:index]

  namespace :admin do
    get :dashboard, to: 'dashboard#index'

    resources :listeners

    resources :schedules do
      member do
        resource :finish, only: [:new, :create], controller: 'schedules/finish'
      end
    end

    resources :talkers, only: [] do
      resource :schedule, only: [:new, :create, :show], controller: 'talkers/schedules'
    end
  end

  root to: 'talkers#new'
end

app/models/listener.rb
class Listener < ApplicationRecord
  validates :name,   presence: true
  validates :email,  presence: true
  validates :phone,  presence: true
  validates :gender, presence: true

  enum gender: { male: 'male', female: 'female' }, _prefix: true

  def to_s
    name
  end
end

app/controllers/admin/listeners_controller.rb
module Admin
  class ListenersController < ApplicationController
    before_action :set_listener, only: [:show, :edit, :update, :destroy]

    def index
      @listeners = Listener.all
    end

    def show
    end

    def new
      @listener = Listener.new
    end

    def edit
    end

    def create
      @listener = Listener.new(listener_params)

      respond_to do |format|
        if @listener.save
          format.html { redirect_to [:admin, @listener], notice: 'Listener was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @listener.update(listener_params)
          format.html { redirect_to [:admin, @listener], notice: 'Listener was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @listener.destroy

      respond_to do |format|
        format.html { redirect_to admin_listeners_url, notice: 'Listener was successfully destroyed.' }
      end
    end

    private

    def set_listener
      @listener = Listener.find(params[:id])
    end

    def listener_params
      params.require(:listener).permit(:name, :email, :phone, :gender)
    end
  end
end

app/views/admin/listeners/_form.html.erb
<%= simple_form_for([:admin, listener], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :gender,
              collection: Listener.genders,
              :label_method => lambda { |item| t("simple_form.options.listener.gender.#{item[0]}") } %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/listeners/edit.html.erb
<h1>Editar ouvinte</h1>

<%= render 'form', listener: @listener %>

<%= link_to 'Visualizar', [:admin, @listener] %> |
<%= link_to 'Voltar', admin_listeners_path %>

app/views/admin/listeners/index.html.erb
<h1>Ouvintes</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th>Telefone</th>
      <th>Gênero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listeners.each do |listener| %>
      <tr>
        <td><%= listener.name %></td>
        <td><%= listener.email %></td>
        <td><%= listener.phone %></td>
        <td><%=t listener.gender, scope: 'simple_form.options.listener.gender' %></td>
        <td><%= link_to 'Visualizar', [:admin, listener] %></td>
        <td><%= link_to 'Editar', edit_admin_listener_path(listener) %></td>
        <td><%= link_to 'Remover', [:admin, listener], method: :delete, data: { confirm: 'Você tem certeza que deseja remover?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo ouvinte', new_admin_listener_path %>

app/views/admin/listeners/new.html.erb
<h1>Novo ouvinte</h1>

<%= render 'form', listener: @listener %>

<%= link_to 'Voltar', admin_listeners_path %>

app/views/admin/listeners/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @listener.name %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @listener.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @listener.phone %>
</p>

<p>
  <strong>Gênero:</strong>
  <%=t @listener.gender, scope: 'simple_form.options.listener.gender' %>
</p>

<%= link_to 'Editar', edit_admin_listener_path(@listener) %> |
<%= link_to 'Voltar', admin_listeners_path %>