config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :talkers,   only: [:new, :create, :show]
  resources :schedules, only: [:index]

  namespace :admin do
    get :dashboard, to: 'dashboard#index'

    resources :listeners

    resources :schedules do
      member do
        resource :finish, only: [:new, :create], controller: 'schedules/finish'
      end
    end

    resources :talkers, only: [] do
      resource :schedule, only: [:new, :create, :show], controller: 'talkers/schedules'
    end
  end

  root to: 'talkers#new'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :listener
  belongs_to :talker, required: false

  validates :listener,     presence: true
  validates :scheduled_to, presence: true
  validates :room_url,     presence: true, format: URI::regexp(%w(http https))

  scope :near,               -> { where(arel_table[:scheduled_to].gt(Time.current)) }
  scope :pending_occurrence, -> { where(occurred_at: nil).where(arel_table[:scheduled_to].lt(Time.current)) }
  scope :available, ->(gender = nil) do
    gender = Listener.genders.keys if gender.nil? or gender == 'indifferent'

    joins(:listener)
      .where(talker_id: nil)
      .where(listeners: { gender: gender })
  end
  scope :remindable, -> do
    two_hours_reminder_base = Time.current + 2.hours
    two_hours_reminder_interval = two_hours_reminder_base.beginning_of_hour..two_hours_reminder_base.end_of_hour
    one_day_reminder_base = Time.current + 1.day
    one_day_reminder_interval = one_day_reminder_base.beginning_of_hour..one_day_reminder_base.end_of_hour

    where(occurred_at: nil).
      where.not(listener_id: nil).
      where.not(talker_id: nil).
      where(scheduled_to: two_hours_reminder_interval).or(where(scheduled_to: one_day_reminder_interval))
  end

  after_initialize do
    self.room_url ||= "https://meet.jit.si/athento-#{Digest::SHA1.hexdigest(Time.current.to_f.to_s)[0..10]}"
  end

  delegate :name, to: :listener

  def occurred?
    occurred_at.present?
  end
end

app/controllers/admin/schedules/finish_controller.rb
module Admin
  module Schedules
    class FinishController < ApplicationController
      def new
        @schedule = Schedule.pending_occurrence.find(params[:id])
      end

      def create
        @schedule = Schedule.pending_occurrence.find(params[:id])
        finisher = ::ScheduleFinisher.new(@schedule, finish_params)

        respond_to do |format|
          if finisher.call
            format.html { redirect_to admin_schedule_path(@schedule), notice: 'Escuta empática finalizada com sucesso.' }
          else
            format.html { render :new }
          end
        end
      end

      private


      def finish_params
        params.require(:schedule).permit(:occurred_at, :duration)
      end
    end
  end
end

app/controllers/admin/schedules_controller.rb
module Admin
  class SchedulesController < ApplicationController
    before_action :set_schedule, only: [:show, :edit, :update, :destroy]

    def index
      @listeners = Listener.order(name: :asc).all
      @schedules = Schedule.includes(:listener).order(scheduled_to: :asc).page(params[:page]).all
      @schedules = @schedules.where(listener_id: params[:listener_id]) if params[:listener_id].present?
    end

    def show
    end

    def new
      @schedule = Schedule.new
    end

    def edit
    end

    def create
      @schedule = Schedule.new(schedule_params)

      respond_to do |format|
        if @schedule.save
          format.html { redirect_to [:admin, @schedule], notice: 'Schedule was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @schedule.update(schedule_params)
          format.html { redirect_to [:admin, @schedule], notice: 'Schedule was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @schedule.destroy

      respond_to do |format|
        format.html { redirect_to admin_schedules_url, notice: 'Schedule was successfully destroyed.' }
      end
    end

    private

    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    def schedule_params
      params.require(:schedule).permit(:listener_id, :talker_id, :scheduled_to, :room_url, :occurred_at, :duration)
    end
  end
end

app/controllers/admin/talkers/schedules_controller.rb
module Admin
  module Talkers
    class SchedulesController < ApplicationController
      before_action :load_dependencies, only: [:new, :create]

      def new
      end

      def create
        @schedule = @available_schedules.find(params[:schedule_id])
        scheduler = ::TalkerScheduler.new(@talker, @schedule)

        respond_to do |format|
          if scheduler.call
            format.html { redirect_to admin_talker_schedule_path(scheduler.talker), notice: 'Schedule was successfully updated.' }
          else
            format.html { render :new }
          end
        end
      end

      def show
        @talker = Talker.find(params[:talker_id])
        @schedule = @talker.schedule
      end

      private

      def load_dependencies
        @talker = Talker.without_schedule.find(params[:talker_id])
        @available_schedules = Schedule.available
      end
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.where(scheduled_to: 1.day.from_now..12.days.from_now).available(params[:gender]).order(scheduled_to: :asc)

    respond_to do |format|
      format.json { render json: @schedules }
      format.js   { render layout: false }
    end
  end
end

app/views/admin/schedules/_form.html.erb
<%= simple_form_for([:admin, schedule], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.association :listener, collection: Listener.order('name ASC') %>
  <%= f.input :scheduled_to, as: :date_time_picker %>
  <%= f.input :room_url, hint: "Use #{link_to 'meet.jit.si', 'https://meet.jit.si', target: '_blank'} to generate a room url".html_safe %>
  <%= f.association :talker %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/schedules/edit.html.erb
<h1>Editar agendamento</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Visualizar', [:admin, @schedule] %> |
<%= link_to 'Voltar', admin_schedules_path %>

app/views/admin/schedules/index.html.erb
<h1>Agendamentos</h1>

<%= form_tag admin_schedules_path, method: :get do %>
  <label>Filtrar por ouvinte:</label>

  <%=
    select_tag(
      :listener_id,
      options_from_collection_for_select(@listeners, :id, :name, selected: params[:listener_id]),
      include_blank: true
    )
  %>

  <%= submit_tag "Filtrar" %>
<% end %>

<table class='table'>
  <thead>
    <tr>
      <th>Ouvinte</th>
      <th>Falante</th>
      <th>Agendado para</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.listener %></td>
        <td><%= schedule.talker %></td>
        <td><%=l schedule.scheduled_to, format: :short %></td>
        <td><%= link_to 'Visualizar', [:admin, schedule] %></td>
        <td><%= link_to 'Editar', edit_admin_schedule_path(schedule) %></td>
        <td><%= link_to 'Remover', [:admin, schedule], method: :delete, data: { confirm: 'Você tem certeza que deseja remover?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= paginate @schedules, theme: 'twitter-bootstrap-3' %>
</p>

<%= link_to 'Novo agendamento', new_admin_schedule_path %>

app/views/admin/schedules/new.html.erb
<h1>Novo agendamento</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Voltar', admin_schedules_path %>

app/views/admin/schedules/show.html.erb
<p>
  <strong>Ouvinte:</strong>
  <%= @schedule.listener %>
</p>

<p>
  <strong>Falante:</strong>
  <%= @schedule.talker %>
</p>

<p>
  <strong>Agendado para:</strong>
  <%=l @schedule.scheduled_to, format: :short %>
</p>

<p>
  <strong>Endereço da sala:</strong>
  <%= link_to @schedule.room_url, @schedule.room_url %>
</p>

<% if @schedule.occurred? %>
  <p>
    <strong>Ocorreu em:</strong>
    <%=l @schedule.occurred_at, format: :short %>
  </p>

  <p>
    <strong>Duração:</strong>
    <%= @schedule.duration %>
  </p>
<% end %>

<%= link_to 'Editar', edit_admin_schedule_path(@schedule) %> |
<%= link_to 'Voltar', admin_schedules_path %>