config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :talkers,   only: [:new, :create, :show]
  resources :schedules, only: [:index]

  namespace :admin do
    get :dashboard, to: 'dashboard#index'

    resources :listeners

    resources :schedules do
      member do
        resource :finish, only: [:new, :create], controller: 'schedules/finish'
      end
    end

    resources :talkers, only: [] do
      resource :schedule, only: [:new, :create, :show], controller: 'talkers/schedules'
    end
  end

  root to: 'talkers#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Athento</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Athento', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li><%= link_to 'Dashboard', admin_dashboard_path %></li>
            <li><%= link_to 'Agendamentos', admin_schedules_path %></li>
            <li><%= link_to 'Ouvintes', admin_listeners_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
          </ul>
        <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <p class='notice'><%= notice %></p>
      <p class='alert'><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>